version: 2
jobs:
  build-and-test:
    macos:
      xcode: "8.2.1"
    shell: /bin/bash --login -eo pipefail

    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - run: sleep 10000
      - run: sudo gem install bundler
      - run: bundle install
      # - run: bundle exec fastlane tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan --sdk iphonesimulator --destination "platform=iOS Simulator,name=iPhone 6,OS=11.2"
          environment:
            SCAN_DEVICE: iPhone 6
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8
            SCAN_SCHEME: todoly
            platform: iOS Simulator

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
